customhost = "employee1.cwxhqawvre8g.us-east-1.rds.amazonaws.com"
customuser = "aws_user"
custompass = "Bait3273"
customdb = "employee1"
custombucket = "thanaash-leaveform"
customregion = "us-east-1"
